name: Build Python Wheels

permissions:
  contents: write  

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build wheels
        run: uv build
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl  # Assumes wheels are created in dist/
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}